### ISSUE TITLE
Problem with kitti dataset

### ISSUE THREAD

**Issue by Gatsby23** [zpw6106/tloam#1]

**Comment by Gatsby23** [comment]
Hi, it's excellent work. But, there are some problems with the kitti 00 sequences. This is my result with default parameter 
![Kitti_accuracy](https://user-images.githubusercontent.com/18000675/121799781-9560ae00-cc60-11eb-885a-7c26bea21ca5.png)
Could you tell me why?

**Comment by zhoupengwei** [comment]
@Gatsby23  Thank you for your attention to our work. There may be several reasons:
1. In our method, different environment features have different convergence rates, which may lead to the end of optimization ahead of time. For urban scenes such as seq00, the optimization will be terminated only when the planar features converge. To this end, I update part of the configuration and source code. 
2. In the current default parameter configuration, I reduce the number of feature points added to the optimization function, which leads to the decline of some precision.
3. At present, the accuracy of the algorithm is mainly affected by the height direction (Z-axis), which is mainly due to the low vertical resolution of lidar, it can not provide enough observation. You can observe our optimized curve eg. Y-axis ( camera frame) to get a more intuitive understanding in the README.
4. At present, our method does not add loop detection and additional constraints.
This is the result of my test for the current version.
![test_86](https://user-images.githubusercontent.com/55874402/121810507-c0b0c080-cc93-11eb-8009-7b3e450ea641.png)

**Comment by Gatsby23** [comment]
> @Gatsby23 Thank you for your attention to our work. There may be several reasons:
> 
> 1. In our method, different environment features have different convergence rates, which may lead to the end of optimization ahead of time. For urban scenes such as seq00, the optimization will be terminated only when the planar features converge. To this end, I update part of the configuration and source code.
> 2. In the current default parameter configuration, I reduce the number of feature points added to the optimization function, which leads to the decline of some precision.
> 3. At present, the accuracy of the algorithm is mainly affected by the height direction (Z-axis), which is mainly due to the low vertical resolution of lidar; it can not provide enough observation. You can observe our optimized curve eg. Y-axis ( camera frame) to get a more intuitive understanding in the README.
> 4. At present, our method does not add loop detection and additional constraints.
>    This is the result of my test for the current version.
>    ![test_86](https://user-images.githubusercontent.com/55874402/121810507-c0b0c080-cc93-11eb-8009-7b3e450ea641.png)

Thank you for your nice reply. But How to achieve the performance in the paper? It looks really great. Are there some parameter optimization skills in it?
![image](https://user-images.githubusercontent.com/18000675/121811322-9f9d9f00-cc96-11eb-8114-c51d18f02b75.png)

**Comment by zhoupengwei** [comment]
@Gatsby23 There are some parameters that can improve performance include:
1. The minimum number of categories after DCVC segmentation.
2. Different downsampling methods
3. The number of various features added to the optimization and their distribution. For example, we want to add non-ground features to the optimization process as vertical as possible. This can better constrain the x, y, yaw orientation components.
4. TLS related optimization parameters.
The results of some scenarios in this paper are the optimal results of many experiments. In fact, it mainly depends on the convergence of the height direction (y, pitch, roll). My experimental raw data are stored in the doc folder. In addition, I am working hard to solve this part of the LiDAR-only Odometry. it is the main problem for most frameworks. If there is any latest progress, I will update it in time.

**Comment by Gatsby23** [comment]
> * The number of various features added to the optimization and their distribution. For example, we want to add non-ground features to the optimization process as vertical as possible. This can better constrain the x, y, yaw orientation components.

Thank you for your nice reply. Thank you very much!

**Comment by jiu876** [comment]
@Gatsby23  hi,when I run the code,at frame 3246, the code will stop running, have you encountered a similar situation?
![屏幕截图 2021-11-16 16:12:39](https://user-images.githubusercontent.com/44089510/141949007-4a168ed3-5536-4594-9ac7-b5bbca45caa8.png)

**Comment by YangSiri** [comment]
Hi, @zpw6106 

I think you've done a great work and your code is clear. But i wonder the meaning of _'gnc_factor'_ parameter. Could you please give me a hint on how it influence the results?

**Comment by Pamphlett** [comment]
@YangSiri 
Hi, `gnc_factor` is a noise modeling parameter in graduated non-convexity.
Please refer to the following paper [Graduated Non-Convexity for Robust Spatial Perception: From Non-Minimal Solvers to Global Outlier Rejection](https://arxiv.org/pdf/1909.08605.pdf).

**Comment by YangSiri** [comment]
@Pamphlett 

Thank you very much~
