### ISSUE TITLE
关于地面法向量的问题

### ISSUE THREAD

**Issue by Gatsby23** [zpw6106/tloam#2]
![image](https://user-images.githubusercontent.com/18000675/122411285-36c86680-cfb7-11eb-8bea-be492f03725d.png)
关于这里地面法向量的计算，我没有太弄懂，为什么会计算三个主轴向量（代表的物理意义是什么？）后面的权重累和又代表什么？

**Comment by zhoupengwei** [comment]
@Gatsby23 Because we don't know the distribution of set points in advance, we need to calculate three principal axes. Geometrically, we find a normal vector that is as perpendicular to all the points in the set as possible. It is equivalent to zero inner product. A more detailed derivation is as follows:
![E43A58279BDBC452004BCE098AED59EF](https://user-images.githubusercontent.com/55874402/122506942-e510f200-d031-11eb-9ce9-2175175d8c77.png)

**Comment by Gatsby23** [comment]
Thank you for your nice replay, thank you very much!

**Comment by gackes** [comment]
Thanks for your work and answer! @zpw6106 
I am confused about the three normal vector. Shouldn't they be in the same direction?

**Comment by zhoupengwei** [comment]
@gackes They are different directions and the final normal vector is the weighted vector sum of the three principal axis vectors.

**Comment by gackes** [comment]
In my mind , I think that x + by + cz + d = 0 and ax + y + cz +d =0 are consistent. So the results should be same. Why we can work out different results? Is there any different mathematical meaning about the there directions except for the normal vector of plane? @zpw6106
